[package]
name = "mini_os"
version = "0.1.0"
authors = ["kenta7777 <k.hasegw7@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
