[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

# specify build target without `--target x86_64-mini_os.json`
[build]
target = "x86_64-mini_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"